services:
  postgres:
    image: postgres:latest
    container_name: wb-orders
    environment:
      POSTGRES_USER: wbuser
      POSTGRES_PASSWORD: wbpassword
      POSTGRES_DB: wbdatabase
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wbtech_network

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://kafka1:29092,CONTROLLER://kafka1:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka1:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka1:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'hRM4jyLm5jxYugExUhDFOA=='
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - kafka_data:/tmp/kraft-combined-logs
    networks:
      - wbtech_network
    user: root

  schema-registry:
    image: confluentinc/cp-schema-registry
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka1:29092'
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
    depends_on:
      - kafka1
    networks:
      - wbtech_network

  ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:29092
      - KAFKA_CLUSTERS_0_NAME=kraft
    ports:
      - "8080:8080"
    networks:
      - wbtech_network
  app:
    build:
      context: . # current dir
      dockerfile: Dockerfile
    container_name: wbtech-kafka
    environment:
      - CONFIG_PATH=/app/docker.yaml
    ports:
      - "8089:8089"
    networks:
      - wbtech_network
    depends_on:
      - kafka1
      - schema-registry

networks:
  wbtech_network:
    driver: bridge

volumes:
  postgres_data:
  kafka_data:
