// Code generated by mockery v2.48.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Deserializer is an autogenerated mock type for the Deserializer type
type Deserializer struct {
	mock.Mock
}

// DeserializeInto provides a mock function with given fields: topic, message, v
func (_m *Deserializer) DeserializeInto(topic string, message []byte, v interface{}) error {
	ret := _m.Called(topic, message, v)

	if len(ret) == 0 {
		panic("no return value specified for DeserializeInto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte, interface{}) error); ok {
		r0 = rf(topic, message, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeserializer creates a new instance of Deserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeserializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Deserializer {
	mock := &Deserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
